/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import obligatorio2.Restoran;
import obligatorio2.*;

/**
 *
 * @author FAMR
 */
public class Principal extends javax.swing.JFrame {
    ImageIcon check= new ImageIcon(getClass().getResource("/interfaz/Imagenes/checkmark.png"));
    ImageIcon noCheck= new ImageIcon(getClass().getResource("/interfaz/Imagenes/noCheck.png"));
    ImageIcon fondo= new ImageIcon(getClass().getResource("/interfaz/Imagenes/fondo.jpg"));
           String eID="";
           String eNombre="";
           String eDireccion="";
           String eHoraApertura="";
           String eHoraCierre="";
           
                  
            
    private Obligatorio2 modelo;
    public Principal(Obligatorio2 unModelo) {
       this.modelo=unModelo;
      this.setSize(500,500);
   
        initComponents();
        tablaRestorant.addMouseListener(new MouseAdapter(){
            DefaultTableModel model= new DefaultTableModel();
            @Override
            public void mouseClicked(MouseEvent e){
             int i = tablaRestorant.getSelectedRow();
           eID= tablaRestorant.getValueAt(i, 0).toString();
           eNombre=(tablaRestorant.getValueAt(i, 1).toString());
           eDireccion=(tablaRestorant.getValueAt(i, 2).toString());
           eHoraApertura=(tablaRestorant.getValueAt(i, 3).toString());
           eHoraCierre=(tablaRestorant.getValueAt(i, 4).toString());
          
                  
            }
        });
    
    }
 @Override
       public void paintComponents (Graphics  g){
           g.drawImage(fondo.getImage(),0, 0,500,500, null);
           super.printComponents(g);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelFichaRestorant = new javax.swing.JPanel();
        panelTextos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRestorant = new javax.swing.JTable();
        panelDatos = new javax.swing.JPanel();
        txtDireccionRestorant = new javax.swing.JTextField();
        txtHoraApertura = new javax.swing.JTextField();
        comboComidas = new javax.swing.JComboBox<>();
        txtHoraCierre = new javax.swing.JTextField();
        txtNombreRestaurant = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnRegistrarRestorant = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtEditarNombre = new javax.swing.JTextField();
        txtEditarHoraApertura = new javax.swing.JTextField();
        txtEditarHoraCierre = new javax.swing.JTextField();
        txtEditarDireccion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboComidasEditar = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFichaRestorant.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Nombre");

        jLabel2.setText("Dirección");

        jLabel3.setText("Hora Apertura");

        jLabel4.setText("Hora Cierre");

        jLabel5.setText("Tipo de Comidas");

        jLabel6.setText("ID");

        javax.swing.GroupLayout panelTextosLayout = new javax.swing.GroupLayout(panelTextos);
        panelTextos.setLayout(panelTextosLayout);
        panelTextosLayout.setHorizontalGroup(
            panelTextosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelTextosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        panelTextosLayout.setVerticalGroup(
            panelTextosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tablaRestorant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección", "Hora Apertura", "Hora Cierre", "Tipo Comida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaRestorant.setRowHeight(30);
        jScrollPane2.setViewportView(tablaRestorant);

        txtDireccionRestorant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionRestorantKeyTyped(evt);
            }
        });

        txtHoraApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraAperturaActionPerformed(evt);
            }
        });
        txtHoraApertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraAperturaKeyTyped(evt);
            }
        });

        comboComidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Vegetariano  ", "Macrobiótico", "De pescados y mariscos", "Carnes Rojas y Aves", "Todo tipo de comidas", "Otro" }));
        comboComidas.setToolTipText("");
        comboComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComidasActionPerformed(evt);
            }
        });

        txtHoraCierre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraCierreKeyTyped(evt);
            }
        });

        txtNombreRestaurant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreRestaurantFocusLost(evt);
            }
        });
        txtNombreRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRestaurantActionPerformed(evt);
            }
        });
        txtNombreRestaurant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreRestaurantKeyTyped(evt);
            }
        });

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        lblNombre.setMaximumSize(new java.awt.Dimension(30, 30));
        lblNombre.setMinimumSize(new java.awt.Dimension(30, 30));
        lblNombre.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDireccionRestorant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtNombreRestaurant, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtHoraCierre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(txtHoraApertura, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombreRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(txtDireccionRestorant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(comboComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrarRestorant.setText("Registrar");
        btnRegistrarRestorant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRestorantActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtEditarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarNombreKeyTyped(evt);
            }
        });

        txtEditarHoraApertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarHoraAperturaKeyTyped(evt);
            }
        });

        txtEditarHoraCierre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarHoraCierreKeyTyped(evt);
            }
        });

        txtEditarDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarDireccionKeyTyped(evt);
            }
        });

        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        jLabel7.setText("Nombre");

        jLabel8.setText("Hora Apertura");

        jLabel9.setText("Dirección");

        jLabel10.setText("Hora Cierre");

        comboComidasEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Vegetariano  ", "Macrobiótico", "De pescados y mariscos", "Carnes Rojas y Aves", "Todo tipo de comidas", "Otro" }));
        comboComidasEditar.setToolTipText("");
        comboComidasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComidasEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtEditarDireccion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEditarHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(comboComidasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEditarHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboComidasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditarHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditarHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(txtEditarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFichaRestorantLayout = new javax.swing.GroupLayout(panelFichaRestorant);
        panelFichaRestorant.setLayout(panelFichaRestorantLayout);
        panelFichaRestorantLayout.setHorizontalGroup(
            panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichaRestorantLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addGroup(panelFichaRestorantLayout.createSequentialGroup()
                        .addComponent(panelTextos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFichaRestorantLayout.createSequentialGroup()
                                .addComponent(btnRegistrarRestorant)
                                .addGap(46, 46, 46)
                                .addComponent(btnEditar)
                                .addGap(48, 48, 48)
                                .addComponent(btnBorrar)
                                .addGap(56, 56, 56)
                                .addComponent(btnSalir))
                            .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFichaRestorantLayout.setVerticalGroup(
            panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichaRestorantLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTextos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelFichaRestorantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarRestorant)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar)
                    .addComponent(btnSalir))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ficha de Restorant", panelFichaRestorant);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("FichaRestorant");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboComidasActionPerformed

    private void txtHoraAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraAperturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraAperturaActionPerformed

    private void txtNombreRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRestaurantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRestaurantActionPerformed

    private void btnRegistrarRestorantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRestorantActionPerformed
     if(validarRestorant()){
      Restoran restoran=new Restoran(Integer.parseInt(txtID.getText()),txtNombreRestaurant.getText(),txtDireccionRestorant.getText(),Integer.parseInt(txtHoraApertura.getText()),Integer.parseInt(txtHoraCierre.getText()),comboComidas.getSelectedItem().toString());
      modelo.agregarRestoran(restoran);
      mostrarMatriz();
      JOptionPane.showMessageDialog(null,"Se ha agregado una nueva Ficha!!");
      txtID.setText("");
      txtNombreRestaurant.setText("");
      txtDireccionRestorant.setText("");
      txtHoraApertura.setText("");
      txtHoraCierre.setText("");
      
    }//GEN-LAST:event_btnRegistrarRestorantActionPerformed
    }
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
         if(eNombre.equals("")||eID.equals("")){
      JOptionPane.showMessageDialog(null,"Por favor seleccione de la tabla el Restorant a borrar!!");
               
     }else{
        for(int i=0;i <modelo.getListaRestoranes().size();i++){
            if(eNombre == modelo.getListaRestoranes().get(i).getNombre()){
               modelo.getListaRestoranes().remove(i);
        }
            
        }
        mostrarMatriz();
         }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     if(eNombre.equals("")||eID.equals("")){
      JOptionPane.showMessageDialog(null,"Por favor seleccione de la tabla el Restorant a editar!!");
               
     }else{
     txtEditarNombre.setText(eNombre);
     txtEditarDireccion.setText(eDireccion);
     txtEditarHoraApertura.setText(eHoraApertura);
     txtEditarHoraCierre.setText(eHoraCierre);
     lblID.setText(eID);
     
     } 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void comboComidasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComidasEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboComidasEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(validarEditarRestorant()){
        for(int i=0;i <modelo.getListaRestoranes().size();i++){
            if(Integer.parseInt(lblID.getText())== modelo.getListaRestoranes().get(i).getIdRestorant()){
               modelo.getListaRestoranes().get(i).setNombre(txtEditarNombre.getText());
               modelo.getListaRestoranes().get(i).setDireccion(txtEditarDireccion.getText());
               modelo.getListaRestoranes().get(i).setApertura(Integer.parseInt(txtEditarHoraApertura.getText()));
               modelo.getListaRestoranes().get(i).setCierre(Integer.parseInt(txtEditarHoraCierre.getText()));
               modelo.getListaRestoranes().get(i).setComida(comboComidasEditar.getSelectedItem().toString());
               
            }
        }
        lblID.setText("ID");
      txtEditarNombre.setText("");
      txtEditarDireccion.setText("");
      txtEditarHoraApertura.setText("");
      txtEditarHoraCierre.setText("");
      mostrarMatriz();
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreRestaurantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreRestaurantKeyTyped
      if(txtNombreRestaurant.getText().length()>=20){
          evt.consume();
      }
        char tipoTecla=evt.getKeyChar();
      if(Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtNombreRestaurantKeyTyped

    private void txtDireccionRestorantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionRestorantKeyTyped
       if(txtDireccionRestorant.getText().length()>=20){
          evt.consume();
      }
        char tipoTecla=evt.getKeyChar();
      if(Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtDireccionRestorantKeyTyped

    private void txtHoraAperturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraAperturaKeyTyped
       if(txtHoraApertura.getText().length()>=5){
          evt.consume();
      }
        char tipoTecla=evt.getKeyChar();
      if(!Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtHoraAperturaKeyTyped

    private void txtHoraCierreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraCierreKeyTyped
       if(txtHoraCierre.getText().length()>=5){
          evt.consume();
       }
        char tipoTecla=evt.getKeyChar();
      if(!Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtHoraCierreKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
       if(txtID.getText().length()>=5){
          evt.consume();
       }
        char tipoTecla=evt.getKeyChar();
      if(!Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtEditarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarNombreKeyTyped
        if(txtEditarNombre.getText().length()>=20){
          evt.consume();
      }
        char tipoTecla=evt.getKeyChar();
      if(Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtEditarNombreKeyTyped

    private void txtEditarDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarDireccionKeyTyped
          if(txtEditarDireccion.getText().length()>=20){
          evt.consume();
      }
        char tipoTecla=evt.getKeyChar();
      if(Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtEditarDireccionKeyTyped

    private void txtEditarHoraCierreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarHoraCierreKeyTyped
        if(txtEditarHoraCierre.getText().length()>=5){
          evt.consume();
       }
        char tipoTecla=evt.getKeyChar();
      if(!Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtEditarHoraCierreKeyTyped

    private void txtEditarHoraAperturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarHoraAperturaKeyTyped
        if(txtHoraApertura.getText().length()>=5){
          evt.consume();
       }
        char tipoTecla=evt.getKeyChar();
      if(!Character.isDigit(tipoTecla)){
      evt.consume();
      }
    }//GEN-LAST:event_txtEditarHoraAperturaKeyTyped

    private void txtNombreRestaurantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreRestaurantFocusLost
        if(!txtNombreRestaurant.getText().equals("")){
            lblNombre.setIcon(check);
        } else{
             lblNombre.setIcon(noCheck);       
        }
        
    }//GEN-LAST:event_txtNombreRestaurantFocusLost
public void  mostrarMatriz()
{
 String matriz[][]= new String[modelo.getListaRestoranes().size()][6];
for(int i=0;i <modelo.getListaRestoranes().size();i++){
    matriz[i][0]=String.valueOf(modelo.getListaRestoranes().get(i).getIdRestorant());
    matriz[i][1]=modelo.getListaRestoranes().get(i).getNombre();
    matriz[i][2]=modelo.getListaRestoranes().get(i).getDireccion();
    matriz[i][3]=String.valueOf(modelo.getListaRestoranes().get(i).getApertura());
    matriz[i][4]=String.valueOf(modelo.getListaRestoranes().get(i).getCierre());
    matriz[i][5]=modelo.getListaRestoranes().get(i).getComida();
}
 tablaRestorant.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "ID", "Nombre", "Dirección", "Hora Apertura", "Hora Cierre", "Tipo Comida"
            }
        )) ;
}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal(modelo).setVisible(true);
//            }
//        });
//    }
 public boolean validarRestorant() {
     boolean ok=true;
   
     
if(txtNombreRestaurant.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese el Nombre!!");
               return false;     
   }
if(txtDireccionRestorant.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la Dirección!!");
               return false;     
   }
if(txtHoraApertura.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la Hora de Apertura!!");
               return false;     
   }
if(txtHoraCierre.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la Hora de Cierre!!");
               return false;     
   }
if(comboComidas.getSelectedItem().toString().equals("Seleccione una opción")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese un Tipo de Comida!!");
               return false;     
   }
if(txtID.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese el ID!!");
               return false;
     }
     for(int i=0;i <modelo.getListaRestoranes().size();i++){
            if(Integer.parseInt(txtID.getText())== modelo.getListaRestoranes().get(i).getIdRestorant()){
               JOptionPane.showMessageDialog(null,"El ID ingresado ya existe,por favor ingrese otro ID!!");
               return false;
    }
   }
return ok;
 }

 public boolean validarEditarRestorant() {
     boolean ok=true; 
if(txtEditarNombre.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese el nuevo Nombre!!");
               return false;     
   }
if(txtEditarDireccion.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la nueva Dirección!!");
               return false;     
   }
if(txtEditarHoraApertura.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la nueva Hora de Apertura!!");
               return false;     
   }
if(txtEditarHoraCierre.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese la nueva Hora de Cierre!!");
               return false;     
   }
if(comboComidasEditar.getSelectedItem().toString().equals("Seleccione una opción")){
         JOptionPane.showMessageDialog(null,"Por favor ingrese el nuevo Tipo de Comida!!");
               return false;     
   }
return ok;
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistrarRestorant;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboComidas;
    private javax.swing.JComboBox<String> comboComidasEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelFichaRestorant;
    private javax.swing.JPanel panelTextos;
    private javax.swing.JTable tablaRestorant;
    private javax.swing.JTextField txtDireccionRestorant;
    private javax.swing.JTextField txtEditarDireccion;
    private javax.swing.JTextField txtEditarHoraApertura;
    private javax.swing.JTextField txtEditarHoraCierre;
    private javax.swing.JTextField txtEditarNombre;
    private javax.swing.JTextField txtHoraApertura;
    private javax.swing.JTextField txtHoraCierre;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreRestaurant;
    // End of variables declaration//GEN-END:variables
}


